baseURL = "https://juliasolorzano.com"
languageCode = "en-us"
title = "Julia Solórzano"

[params]
  description = "Julia Solórzano is a design leader and technologist specializing in GIS, web and mobile development, federated identity, and strategic leadership. With 20+ years in tech, she builds high-performing teams and helps people create seamless digital experiences."
  author = "Julia Solórzano"

[permalinks]
  posts = "/blog/:year/:month/:day/:slug/"

[markup.goldmark.renderer]
  unsafe = true

[markup.highlight]
  style = "monokai"

[markup.tableOfContents]
  startLevel = 2
  endLevel = 3
  ordered = false

[outputFormats.RSS]
  baseName = "feed"

[taxonomies]

[sitemap]
  changeFreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

[outputs]
  home = ["HTML", "RSS"]
  section = ["HTML"]
